### PR TITLE
Adds additional linting to make description required (solves #264)

### PR DESCRIPTION
**Pull request by miike**
This adds support for the description property and adds a new severity level for linting that makes the description property mandatory. Related: #264

### CODE REVIEW

**Comment by snowplowcla** [comment]
@miike has signed the Software Grant and Corporate Contributor License Agreement

**Comment by miike** [comment]
Agreed - that was something I was thinking about while implementing this. I wonder if it should be passed in via CLI or possibly have a minimal configuration file for the linter.

**Comment by chuwy** [comment]
I'm leaning towards CLI option. Something like `--checks description,size,some_other_check` and `--checks all`. I think scope of igluctl is too tiny to have a dedicated configuration format.

**Comment by miike** [comment]
Fair enough - a configuration file is probably overkill at this point.

**Comment by oguzhanunlu** [comment]
Cherry-picked to #309, closing.

**Pull request closed without merging**
