### PR TITLE
Release/0.4.0

### PR DESCRIPTION
**Pull request by chuwy**
@Deano could you please review last commit? I'll squash if everything fine with it.

### CODE REVIEW

**Comment by chuwy** [comment]
I also decided to not implement `PartialOrdering` as @fblundun suggested. Because its usage seems very hazy for me http://stackoverflow.com/questions/36791010/purpose-of-partialordering-in-scala-library

**Comment by alexanderdean** [comment]
Okay cool

**Comment by chuwy** [comment]
@alexanderdean this is ready.

**Comment by alexanderdean** [comment]
Has been merged, closing

**Pull request closed without merging**
