### PR TITLE
factor out AWScala - fixes snowplow/iglu#283 

### PR DESCRIPTION
**Pull request by saj1th**
Thanks for the catch! removed it from the build files as well

### CODE REVIEW

**Comment by snowplowcla** [comment]
Confirmed! @saj1th  has signed the Individual Contributor License Agreement. Thanks so much

**Comment by snowplowcla** [comment]
Confirmed! @saj1th  has signed the Individual Contributor License Agreement. Thanks so much

**Comment by chuwy** [comment]
Hi, @saj1th, could you please also rebase your commit history according to our [conventions](https://github.com/snowplow/snowplow/blob/master/CONTRIBUTING.md#commit-hygiene)? E.g. ` igluctl: factor out AWScala (closes #283)`

**Comment by chuwy** [comment]
Hi, @saj1th, could you please also rebase your commit history according to our [conventions](https://github.com/snowplow/snowplow/blob/master/CONTRIBUTING.md#commit-hygiene)? E.g. ` igluctl: factor out AWScala (closes #283)`

**Comment by chuwy** [comment]
Hi, @saj1th, could you please also rebase your commit history according to our [conventions](https://github.com/snowplow/snowplow/blob/master/CONTRIBUTING.md#commit-hygiene)? E.g. ` igluctl: factor out AWScala (closes #283)`

**Comment by chuwy** [comment]
Hi, @saj1th, could you please also rebase your commit history according to our [conventions](https://github.com/snowplow/snowplow/blob/master/CONTRIBUTING.md#commit-hygiene)? E.g. ` igluctl: factor out AWScala (closes #283)`

**Comment by chuwy** [comment]
Hi, @saj1th, could you please also rebase your commit history according to our [conventions](https://github.com/snowplow/snowplow/blob/master/CONTRIBUTING.md#commit-hygiene)? E.g. ` igluctl: factor out AWScala (closes #283)`

**Comment by saj1th** [comment]
sure!

**Comment by chuwy** [comment]
Closing in favor of https://github.com/snowplow/iglu/pull/424. Thanks so much!

**Pull request closed without merging**
