### PR TITLE
Adds field length hinting for email properties

### LINKED ISSUE #257: Schema DDL: generate fixed length for 'email' fields
When a property is specified with email format e.g.,

```
"email": {
  "type": "string",
  "format": "email"
}
```

Iglu should set the data type to varchar(255) rather than relying on the default (4096).

### PR DESCRIPTION
**Pull request by miike**
Fixes #257

### CODE REVIEW

**Comment by chuwy** [comment]
Looks good, scheduling. Thanks @miike.

**Comment by snowplowcla** [comment]
@miike has signed the Software Grant and Corporate Contributor License Agreement

**Comment by miike** [comment]
Thanks all!

**Comment by oguzhanunlu** [comment]
Cherry-picked to #280 .

**Pull request closed without merging**
