### PR TITLE
Switch method order in Scaladoc

### PR DESCRIPTION
**Pull request by miike**
Ensures that Scaladoc matches the class definition. #394

### CODE REVIEW

**Comment by snowplowcla** [comment]
@miike  has signed the Software Grant and Corporate Contributor License Agreement

**Comment by chuwy** [comment]
Thanks @miike! Could you please rename a commit according to match the issue title: `Scala Core: swap SelfDescribingData member names (closes #394)`

**Comment by chuwy** [comment]
Ah sorry, @miike, I just noticed that your commit just swaps them, but content remains unchanged:
"**data** reference to **Schema**" and "**schema** attached **data** instance itself"

**Comment by chuwy** [comment]
Closing in favor of https://github.com/snowplow/iglu/pull/424. Together we nailed this bug! Thanks!

**Pull request closed without merging**
