### PR TITLE
rename Product to Union in jsonschema

### PR DESCRIPTION
**Pull request by Mandelliant**
@chuwy I believe I caught all instances of Product in files under jsonschema - let me know if you have any feedback

### CODE REVIEW

**Comment by chuwy** [comment]
Thanks @Mandelliant! You can check if all instances are fixed by trying compiling the project:

```bash
$ cd iglu/schema-ddl && sbt compile
```

You can get sbt from [here](https://github.com/paulp/sbt-extras).

 I see 8 occurrences left:

```
schema-ddl> compile
[info] Compiling 55 Scala sources to /Users/chuwy/workspace/iglu/0-common/schema-ddl/target/scala-2.12/classes ...
[error] /Users/chuwy/workspace/iglu/0-common/schema-ddl/src/main/scala/com.snowplowanalytics/iglu.schemaddl/FlatSchemaNext.scala:112:17: not found: value Product
[error]       case Some(Product(types)) => types.contains(Object)
[error]                 ^
[error] /Users/chuwy/workspace/iglu/0-common/schema-ddl/src/main/scala/com.snowplowanalytics/iglu.schemaddl/bigquery/Suggestion.scala:34:34: value Product is not a member of object com.snowplowanalytics.iglu.schemaddl.jsonschema.CommonProperties
[error]       case Some(CommonProperties.Product(types)) if withNull(types, CommonProperties.Boolean) =>
[error]                                  ^
[error] /Users/chuwy/workspace/iglu/0-common/schema-ddl/src/main/scala/com.snowplowanalytics/iglu.schemaddl/bigquery/Suggestion.scala:43:34: value Product is not a member of object com.snowplowanalytics.iglu.schemaddl.jsonschema.CommonProperties
[error]       case Some(CommonProperties.Product(types)) if withNull(types, CommonProperties.Integer) =>
[error]                                  ^
[error] /Users/chuwy/workspace/iglu/0-common/schema-ddl/src/main/scala/com.snowplowanalytics/iglu.schemaddl/bigquery/Suggestion.scala:52:34: value Product is not a member of object com.snowplowanalytics.iglu.schemaddl.jsonschema.CommonProperties
[error]       case Some(CommonProperties.Product(types)) if onlyNumeric(types.toSet, true) =>
[error]                                  ^
[error] /Users/chuwy/workspace/iglu/0-common/schema-ddl/src/main/scala/com.snowplowanalytics/iglu.schemaddl/bigquery/Suggestion.scala:54:34: value Product is not a member of object com.snowplowanalytics.iglu.schemaddl.jsonschema.CommonProperties
[error]       case Some(CommonProperties.Product(types)) if onlyNumeric(types.toSet, false)  =>
[error]                                  ^
[error] /Users/chuwy/workspace/iglu/0-common/schema-ddl/src/main/scala/com.snowplowanalytics/iglu.schemaddl/bigquery/Suggestion.scala:56:34: value Product is not a member of object com.snowplowanalytics.iglu.schemaddl.jsonschema.CommonProperties
[error]       case Some(CommonProperties.Product(types)) if withNull(types, CommonProperties.Number) =>
[error]                                  ^
[error] /Users/chuwy/workspace/iglu/0-common/schema-ddl/src/main/scala/com.snowplowanalytics/iglu.schemaddl/bigquery/Suggestion.scala:73:35: value Product is not a member of object com.snowplowanalytics.iglu.schemaddl.jsonschema.CommonProperties
[error]       case (Some(CommonProperties.Product(types)), Some(StringProperties.DateFormat)) if withNull(types, CommonProperties.String) =>
[error]                                   ^
[error] /Users/chuwy/workspace/iglu/0-common/schema-ddl/src/main/scala/com.snowplowanalytics/iglu.schemaddl/bigquery/Suggestion.scala:78:35: value Product is not a member of object com.snowplowanalytics.iglu.schemaddl.jsonschema.CommonProperties
[error]       case (Some(CommonProperties.Product(types)), Some(StringProperties.DateTimeFormat)) if withNull(types, CommonProperties.String) =>
[error]                                   ^
[error] 8 errors found
```

**Comment by Mandelliant** [comment]
Thanks, @chuwy, I'll update and run that test!

**Comment by Mandelliant** [comment]
Addresses #387

**Comment by Mandelliant** [comment]
In `FlatSchemaNext.scala`, line 90: 
` * @return pair of flat and complext lists of subschemas`

@chuwy should that be complex or complete?

**Comment by Mandelliant** [comment]
@chuwy, project compiled:

```
[info] Compiling 55 Scala sources to /Users/anthonymandelli/Repos/iglu/0-common/schema-ddl/target/scala-2.12/classes ...
[info] Non-compiled module 'compiler-bridge_2.12' for Scala 2.12.4. Compiling...
[info]   Compilation completed in 10.512s.
[info] Done compiling.
[success] Total time: 30 s, completed Oct 3, 2018, 8:43:39 AM
```

**Comment by chuwy** [comment]
Thanks @Mandelliant!

> should that be complex or complete?

Complex. But that was not easy to figure out.

Could you please also try `sbt test`? Tests are complied as separate unit, we can still have some instances of `Product` there.

**Comment by chuwy** [comment]
Confirmed, tests are green! Is it your first Scala contribution, @Mandelliant? Also if possible could you please [squash](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) these three commits into single `Schema DDL: rename Product type to Union in jsonschema (close #387)`?

**Comment by Mandelliant** [comment]
@chuwy yup, this is my first Scala contribution! I'll work on squashing them and let you know when it's done

**Comment by Mandelliant** [comment]
@chuwy I think we're good to go

**Comment by chuwy** [comment]
Thanks @Mandelliant. Squash is not exactly right, but feel free to leave it to me if you don't want to bother (or you can reach me on Slack and we can do it together).

**Comment by chuwy** [comment]
Closing in favor of #442. Thanks @Mandelliant!

**Pull request closed without merging**
