### PR TITLE
Added clarifying comma

### PR DESCRIPTION
**Pull request by simlu**
Very minor change, but considering this is the first piece of documentation that your read... I had to read twice to understand :)

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

📝 Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by simlu** [comment]
I'm sorry. How does the signing work? Can I not do this electronically??

**Comment by chuwy** [comment]
Hey @simlu. Of course you can! There's a link with form under "Individual Contributor License Agreement v1.0", you can just submit this form.

Thanks for your contribution!

**Comment by simlu** [comment]
Ah, well hidden. You might want to better clarify that in the auto post creation here...

Anyways, "I signed it!" :)

**Comment by chuwy** [comment]
Hey @oguzhanunlu could you please handle this (ticket, cherry-pick, etc) as soon as @snowplowcla will confirm we have a signature?

**Comment by oguzhanunlu** [comment]
Of course @chuwy , on it.

**Comment by snowplowcla** [comment]
Confirmed @simlu has signed our Individual Contributor License Agreement v1.0, thanks so much

**Comment by oguzhanunlu** [comment]
Cherry-picked to #280

**Pull request closed without merging**
